version: '3.4'

x-env: &env
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_HOST=db
    - POSTGRES_DB=db

services:
  app:
    <<: *env
    build:
      context: .
    command: mix do deps.get, phx.server
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    <<: *env
    image: postgres:10
    volumes:
      - /var/lib/postgresql
      - ./test/files:/files
    ports:
      - 5432:5432

volumes:
  build: {}
  deps: {}
